name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch to match your deployment workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: Jessomadic/checkout@main  # Using your forked action

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: jessomadic/monolithic:latest
